config/routes.rb
Rails.application.routes.draw do
  
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  resources :contactos
  resources :aboutus
  resources :producto_adjuntos
  resources :productos
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'aboutus#index'
  get 'search/create'

  # User authentication
  devise_for :users, controllers: {
    sessions: 'users/sessions',
    passwords: 'users/passwords',
    registrations: 'users/registrations'
  }

end

app/models/producto_adjunto.rb
class ProductoAdjunto < ApplicationRecord
	mount_uploader :avatar, AvatarUploader
	belongs_to :producto
end

app/controllers/producto_adjuntos_controller.rb
class ProductoAdjuntosController < ApplicationController
  before_action :set_producto_adjunto, only: [:show, :edit, :update, :destroy]

  # GET /producto_adjuntos
  # GET /producto_adjuntos.json
  def index
    @producto_adjuntos = ProductoAdjunto.all
  end

  # GET /producto_adjuntos/1
  # GET /producto_adjuntos/1.json
  def show
  end

  # GET /producto_adjuntos/new
  def new
    @producto_adjunto = ProductoAdjunto.new
  end

  # GET /producto_adjuntos/1/edit
  def edit
  end

  # POST /producto_adjuntos
  # POST /producto_adjuntos.json
  def create
    @producto_adjunto = ProductoAdjunto.new(producto_adjunto_params)

    respond_to do |format|
      if @producto_adjunto.save
        format.html { redirect_to @producto_adjunto, notice: 'Producto adjunto was successfully created.' }
        format.json { render :show, status: :created, location: @producto_adjunto }
      else
        format.html { render :new }
        format.json { render json: @producto_adjunto.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /producto_adjuntos/1
  # PATCH/PUT /producto_adjuntos/1.json
  def update
    respond_to do |format|
      if @producto_adjunto.update(producto_adjunto_params)
        format.html { redirect_to @producto_adjunto.producto, notice: 'Producto adjunto was successfully updated.' }
        format.json { render :show, status: :ok, location: @producto_adjunto }
      else
        format.html { render :edit }
        format.json { render json: @producto_adjunto.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /producto_adjuntos/1
  # DELETE /producto_adjuntos/1.json
  def destroy
    @producto_adjunto.destroy
    respond_to do |format|
      format.html { redirect_to producto_adjuntos_url, notice: 'Producto adjunto was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_producto_adjunto
      @producto_adjunto = ProductoAdjunto.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def producto_adjunto_params
      params.require(:producto_adjunto).permit(:producto_id, :avatar)
    end
end

app/helpers/producto_adjuntos_helper.rb
module ProductoAdjuntosHelper
end

app/views/producto_adjuntos/_form.html.erb
<%= image_tag @producto_adjunto.avatar %>
<%= form_for(producto_adjunto) do |f| %>
  <% if producto_adjunto.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(producto_adjunto.errors.count, "error") %> prohibited this producto_adjunto from being saved:</h2>

      <ul>
      <% producto_adjunto.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :avatar %> <br>
    <%= f.file_field :avatar %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/producto_adjuntos/edit.html.erb
<h1>Editing Producto Adjunto</h1>

<%= render 'form', producto_adjunto: @producto_adjunto %>

<% if !current_user.nil? %> 
	<% if current_user.user_role? %>
  		<%= link_to 'Show', @producto_adjunto %> |
		<%= link_to 'Back', producto_adjuntos_path %>
	<% end %>
<% end %>

app/views/producto_adjuntos/index.html.erb
<h1>Producto Adjuntos</h1>

<table>
  <thead>
    <tr>
      <th>Producto</th>
      <th>Avatar</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @producto_adjuntos.each do |producto_adjunto| %>
      <tr>
        <td><%= producto_adjunto.producto_id %></td>
        <td><%=image_tag producto_adjunto.avatar , class: 'img_small'%></td>

        <% if !current_user.nil? %> 
          <% if current_user.user_role? %>
            <td><%= link_to 'Show', producto_adjunto %></td>
            <td><%= link_to 'Edit', edit_producto_adjunto_path(producto_adjunto) %></td>
            <td><%= link_to 'Destroy', producto_adjunto, method: :delete, data: { confirm: 'Are you sure?' } %></td>
          <% end %>
        <% end %>

        
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<% if !current_user.nil? %> 
  <% if current_user.user_role? %>
    <%= link_to 'New Producto Adjunto', new_producto_adjunto_path %>
  <% end %>
<% end %>

app/views/producto_adjuntos/new.html.erb
<h1>New Producto Adjunto</h1>

<%= render 'form', producto_adjunto: @producto_adjunto %>

<% if !current_user.nil? %> 
	<% if current_user.user_role? %>
  		<%= link_to 'Back', producto_adjuntos_path %>
	<% end %>
<% end %>

app/views/producto_adjuntos/show.html.erb
<p>
  <strong>Producto:</strong>
  <%= @producto_adjunto.producto_id %>
</p>

<p>
  <strong>Avatar:</strong>
  <%= @producto_adjunto.avatar %>
</p>

<% if !current_user.nil? %> 
	<% if current_user.user_role? %>
  		<%= link_to 'Edit', edit_producto_adjunto_path(@producto_adjunto) %> |
		<%= link_to 'Back', producto_adjuntos_path %>
	<% end %>
<% end %>