config/routes.rb
Rails.application.routes.draw do
  
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  resources :contactos
  resources :aboutus
  resources :producto_adjuntos
  resources :productos
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'aboutus#index'
  get 'search/create'

  # User authentication
  devise_for :users, controllers: {
    sessions: 'users/sessions',
    passwords: 'users/passwords',
    registrations: 'users/registrations'
  }

end

app/models/producto.rb
class Producto < ApplicationRecord
	has_many :producto_adjuntos
	accepts_nested_attributes_for :producto_adjuntos
end

app/controllers/productos_controller.rb
class ProductosController < ApplicationController
  before_action :set_producto, only: [:show, :edit, :update, :destroy]

  # SKIP authentication
  skip_before_action :authenticate_user!, :only => [:index, :show]

  # GET /productos
  # GET /productos.json
  def index
    @productos = Producto.limit(9)
  end

  # GET /productos/1
  # GET /productos/1.json
  def show
    @producto_adjuntos = @producto.producto_adjuntos.all
  end

  # GET /productos/new
  def new
    @producto = Producto.new
    @producto_adjunto = @producto.producto_adjuntos.build
  end

  # GET /productos/1/edit
  def edit
  end

  # POST /productos
  # POST /productos.json
  def create
    @producto = Producto.new(producto_params)

    respond_to do |format|
      if @producto.save

        #Accept multiple images for Producto
        params[:producto_adjuntos]['avatar'].each do |a|
          @producto_adjunto = @producto.producto_adjuntos.create!(:avatar => a)
        end

        format.html { redirect_to @producto, notice: 'Producto was successfully created.' }
        format.json { render :show, status: :created, location: @producto }
      else
        format.html { render :new }
        format.json { render json: @producto.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /productos/1
  # PATCH/PUT /productos/1.json
  def update
    respond_to do |format|
      if @producto.update(producto_params)
        format.html { redirect_to @producto, notice: 'Producto was successfully updated.' }
        format.json { render :show, status: :ok, location: @producto }
      else
        format.html { render :edit }
        format.json { render json: @producto.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /productos/1
  # DELETE /productos/1.json
  def destroy
    @producto.destroy
    respond_to do |format|
      format.html { redirect_to productos_url, notice: 'Producto was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_producto
      @producto = Producto.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def producto_params
      params.require(:producto).permit(:nombre, :descripcion, :caracteristicas, :especificaciones, :avatar, :es_servicio, :es_propio, :nombre_empresa, :sitio_empresa, :url_prod_empresa, producto_adjuntos_attributes: [:id, :producto_id, :avatar])
    end
end

app/helpers/productos_helper.rb
module ProductosHelper
end

app/views/productos/_form.html.erb
<br>
<%= form_for @producto, :html => {:class => "form-horizontal center"} do |f| %>
  <% if producto.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(producto.errors.count, "error") %> prohibited this producto from being saved:</h2>

      <ul>
      <% producto.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="container special">

      <div class="form-group">
        <%= f.label :nombre, "Nombre", class: "col-md-4 control-label"  %>
          <div class="col-md-6">
        <%= f.text_field :nombre, class: "form-control" %>
          </div>
      </div>

      <div class="form-group">
        <%= f.label :descripcion, "Descripción", class: "col-md-4 control-label"  %>
          <div class="col-md-6">
        <%= f.text_area :descripcion, class: "form-control" %>
          </div>
      </div>

      <div class="form-group">
        <%= f.label :caracteristicas, "Características", class: "col-md-4 control-label"  %>
          <div class="col-md-6">
        <%= f.text_area :caracteristicas, class: "form-control" %>
          </div>
      </div>

      <div class="form-group">
        <%= f.label :especificaciones, "Especificaciones", class: "col-md-4 control-label"  %>
          <div class="col-md-6">
        <%= f.text_area :especificaciones, class: "form-control" %>
          </div>
      </div>

      <%= f.fields_for :producto_adjuntos do |p| %>
        <div class="form-group">
          <%= p.label :avatar, "Imágenes", class: "col-md-4 control-label"  %>
            <div class="col-md-6">
          <%= p.file_field :avatar, :multiple => true, name: "producto_adjuntos[avatar][]" %>
            </div>
        </div>
      <% end %>

      <div class="form-group">
        <%= f.label :es_servicio, "Es servicio", class: "col-md-4 control-label"  %>
          <div class="col-md-1">
        <%= f.check_box :es_servicio, class: "form-control" %>
          </div>
      </div>

      <div class="form-group">
        <%= f.label :es_propio, "", class: "col-md-4 control-label"  %>
          <div class="col-md-1">
        <%= f.check_box :es_propio, class: "form-control" %>
          </div>
      </div>

      <div class="form-group">
        <%= f.label :nombre_empresa, "", class: "col-md-4 control-label"  %>
          <div class="col-md-6">
        <%= f.text_field :nombre_empresa, class: "form-control" %>
          </div>
      </div>

      <div class="form-group">
        <%= f.label :sitio_empresa, "", class: "col-md-4 control-label"  %>
          <div class="col-md-6">
        <%= f.text_field :sitio_empresa, class: "form-control" %>
          </div>
      </div>

      <div class="form-group">
        <%= f.label :url_prod_empresa, "", class: "col-md-4 control-label"  %>
          <div class="col-md-6">
        <%= f.text_field :url_prod_empresa, class: "form-control" %>
          </div>
      </div>

      <div class="row">
        <div class="col-sm-8"></div>
        <div class="col-sm-4">
          <div class="actions">
            <%= f.submit "Enviar", class: "btn btn-default btn-primary" %> 
          </div>
        </div>
      </div>

    
  </div>
<% end %>

app/views/productos/_producto.html.erb
<div class="panel panel-success">
	<strong class="text-primary"><%= producto.nombre %></strong>
	<p class="text-muted"><%= producto.descripcion.truncate(50) %> &nbsp;<%= link_to "Detalle...", producto, :class => "btn btn-success btn-xs" %></p>
</div>

app/views/productos/edit.html.erb
<br><h2 class="text-primary">Editar Producto</h2><br>

<%= render 'form', producto: @producto %>

<% if !current_user.nil? %> 
	<% if current_user.user_role? %>
  		<%= link_to 'Show', @producto %> |
		<%= link_to 'Back', productos_path %>
	<% end %>
<% end %>

app/views/productos/index.html.erb
 <div onended="checkTRM();" class="container special">
  <div class="row">
    <div class="col-sm-6"><br>
      <h2 class="text-primary">Productos y Servicios</h2>
    </div>

    <br><br><br><br>

    <div class="panel panel-primary">
      <div class="panel-heading">
      <center>
        <br>
        <a href="#" class="btn btn-info btn-lg">
          <span class="glyphicon glyphicon-th"></span> Productos 
        </a>
      <span style="padding-left:30px;">&nbsp;</span>
        <a href="#" class="btn btn-info btn-lg">
          <span class="glyphicon glyphicon-th-list"></span> Servicios 
        </a>
      </center>
      </div>
    </div>
    <br><br>

    <div class="container special" style="width: 90%; height: 90%;">

<!-- Example row of columns -->
      <div class="row">
        <% @productos.each do |producto| %>
        <div class="col-lg-3 col-md-4 col-xs-6">
          <table class="own_table">
            <tr align="center">
              <td style="width: 60%; height: 30%;"><br>
                <%= image_tag producto.producto_adjuntos.first.avatar_url , class: 'img_thumb_small' %>
              </td>
            </tr>
            <tr align="center">
              <td style="width: 60%; height: 20%;"><br>
                <h5 class="text-primary"><b><%= producto.nombre.truncate(30) %></b></h5>
              </td>
            </tr>
            <tr>
              <td style="width: 50%; height: 40%; text-decoration: italic; padding-left:10px; padding-right:5px;"><br>
                <p class="text-justify text-muted"><i><%= producto.descripcion.truncate(65) %><br></i></p>
              </td>
            </tr>
            <tr>
              <td style="width: 60%; height: 10%; text-align: center; padding-bottom: 8px;">
              <i><%= link_to 'Detalle', producto , :class => "btn btn-primary" %></i>
                <% if !current_user.nil? %> 
                  <% if current_user.user_role? %>
                    
                    <%= link_to 'Editar', edit_producto_path(producto) , :class => "btn btn-success" %>
                    <%= link_to 'Eliminar', producto, method: :delete, data: { confirm: 'Are you sure?' } , :class => "btn btn-danger" %>
                  <% end %>
                <% end %>
                
              </td>
            </tr>
          </table>
          <br><br>
        </div>
        <%end%>
      </div>
    </div>

<% if !current_user.nil? %> 
  <% if current_user.user_role? %>
    <%= link_to 'New Producto', new_producto_path %>
  <% end %>
<% end %> 

  </div>
</div>

app/views/productos/new.html.erb
<br><h2 class="text-primary">Nuevo Producto</h2><br>

<%= render 'form', producto: @producto %>

<% if !current_user.nil? %> 
	<% if current_user.user_role? %>
  		<%= link_to 'Back', productos_path %>
	<% end %>
<% end %>

app/views/productos/show.html.erb
<div class="container special" style="width: 90%; height: 90%;">

  <div class="row">
    <div class="box">
        <div class="col-lg-12">
            <hr>
            <h3 class="intro-text text-center text-primary">
                <strong><%= @producto.nombre %></strong>
            </h3>
            <hr>
        </div>
        <div class="col-md-6 col-md-4">
          <div class="row">
            <!-- Carousel ========================================== -->
            <div align="center" id="eachProduct" class="carousel slide" data-interval="2000" data-ride="carousel">
              <!-- Indicators -->
              <ol class="carousel-indicators">
                <% @producto_adjuntos.each_with_index do |image, index| %>
                  <li data-target="#eachProduct" data-slide-to="<%= index %>" class="<%= index == 0 ? 'active' : '' %> " style="border: none;background-color: #4286f4;"></li>
                <% end %>
              </ol>

              <div>
              <br>
                <div class="carousel-inner" role="listbox" style="width:100%; height: 200px !important;">
                  <% @producto_adjuntos.each_with_index do |image, index| %> 
                  <% if !index.nil? %>    
                    <div class="item <%= index == 0 ? 'active' : '' %>">
                      <%= image_tag image.avatar_url , class: 'img_thumb_slide_prod' %>
                    </div>
                  <% end %>
                  <% end %>
                </div>

                <a class="left carousel-control" href="#eachProduct" role="button" data-slide="prev">
                  <span class="glyphicon glyphicon-chevron-left text-primary" aria-hidden="true"></span>
                  <span class="sr-only">Previous</span>
                </a>
                <a class="right carousel-control" href="#eachProduct" role="button" data-slide="next">
                  <span class="glyphicon glyphicon-chevron-right text-primary" aria-hidden="true"></span>
                  <span class="sr-only">Next</span>
                </a>
              </div>
            </div><!-- /.carousel -->
          </div>
        </div>
        <br>
        <div class="col-md-6">
            <p class="text-justify"><%= @producto.descripcion %></p>
        </div>
        <div class="clearfix"></div>
      </div>
  </div>
  <br><br>
  <div class="container special" style="width: 90%; height: 90%;">
    <!-- Tabs to include more info about the Product -->
    <ul class="nav nav-tabs">
      <li class="active"><a data-toggle="tab" href="#caract" class="text-primary"><b>Caracter&iacute;sticas</b></a></li>
      <li><a data-toggle="tab" href="#especif" class="text-primary"><b>Especificaciones</b></a></li>
      <li><a data-toggle="tab" href="#masinfo" class="text-primary"><b>M&aacute;s Info</b></a></li>
    </ul>
    <div class="tab-content" style="width: 90%;">
      <div id="caract" class="tab-pane fade in active"><br><center>
        <p class="text-justify"><%= @producto.caracteristicas %></p></center>
      </div>
      <div id="especif" class="tab-pane fade"><br>
        <p class="text-justify"><%= @producto.especificaciones %></p>
      </div>
      <div id="masinfo" class="tab-pane fade"><br>
        <p class="text-justify">
          <% if @producto.es_servicio %>
            <strong>Proveemos este servicio</strong>
          <% else %>
            <% if @producto.es_propio %>
              <strong>Este es un Producto nuestro!</strong>
            <% else %>
              <strong><i>Este es un Producto de: </i></strong>
              <p>
                <strong>Nombre:</strong> <%= @producto.nombre_empresa %><br>
                <strong>Sitio:</strong> <%= @producto.sitio_empresa %><br>
                <strong>Url producto:</strong> <%= @producto.url_prod_empresa %>
              </p>
            <% end %>
          <% end %>
        </p>
      </div>
    </div>
  </div>
</div>

<br><br>

<% if !current_user.nil? %> 
  <% if current_user.user_role? %>
    <%= link_to 'Editar', edit_producto_path(@producto) %> |
    <%= link_to 'Volver', productos_path %>
  <% end %>
<% end %>


<!--script> Solo en caso que se requiera que el slide inicie solo
// Load this when the DOM is ready
$(function(){
  // You used .myCarousel here. 
  // That's the class selector not the id selector,
  // which is #myCarousel
  $('#myProductCarousel').carousel();
});
</script -->