config/routes.rb
Rails.application.routes.draw do
  
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  resources :contactos
  resources :aboutus
  resources :producto_adjuntos
  resources :productos
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'aboutus#index'
  get 'search/create'

  # User authentication
  devise_for :users, controllers: {
    sessions: 'users/sessions',
    passwords: 'users/passwords',
    registrations: 'users/registrations'
  }

end

app/models/aboutu.rb
class Aboutu < ApplicationRecord
	mount_uploader :urlnosotros, AvatarUploader
	mount_uploader :urlmision,   AvatarUploader
	mount_uploader :urlvision,   AvatarUploader
end

app/controllers/aboutus_controller.rb
class AboutusController < ApplicationController
  before_action :set_aboutu, only: [:show, :edit, :update, :destroy]

  # SKIP authentication
  skip_before_action :authenticate_user!, :only => [:index, :show]

  # GET /aboutus
  # GET /aboutus.json
  def index
    @aboutus = Aboutu.all
  end

  # GET /aboutus/1
  # GET /aboutus/1.json
  def show
    aboutu = Aboutu.find(params[:id])
  end

  # GET /aboutus/new
  def new
    @aboutu = Aboutu.new
  end

  # GET /aboutus/1/edit
  def edit
  end

  # POST /aboutus
  # POST /aboutus.json
  def create
    @aboutu = Aboutu.new(aboutu_params)

    respond_to do |format|
      if @aboutu.save
        format.html { redirect_to @aboutu, notice: 'Aboutu was successfully created.' }
        format.json { render :show, status: :created, location: @aboutu }
      else
        format.html { render :new }
        format.json { render json: @aboutu.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /aboutus/1
  # PATCH/PUT /aboutus/1.json
  def update
    respond_to do |format|
      if @aboutu.update(aboutu_params)
        format.html { redirect_to @aboutu, notice: 'Aboutu was successfully updated.' }
        format.json { render :show, status: :ok, location: @aboutu }
      else
        format.html { render :edit }
        format.json { render json: @aboutu.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /aboutus/1
  # DELETE /aboutus/1.json
  def destroy
    @aboutu.destroy
    respond_to do |format|
      format.html { redirect_to aboutus_url, notice: 'Aboutu was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_aboutu
      @aboutu = Aboutu.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def aboutu_params
      params.require(:aboutu).permit(:nombre, :mision, :vision, :descripcion, :contactenos, :copyright, :urlnosotros, :urlmision, :urlvision)
    end
end

app/helpers/aboutus_helper.rb
module AboutusHelper
end

app/views/aboutus/_form.html.erb
<%= form_for(aboutu) do |f| %>
  <% if aboutu.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(aboutu.errors.count, "error") %> prohibited this aboutu from being saved:</h2>

      <ul>
      <% aboutu.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :nombre %>
    <%= f.text_field :nombre %>
  </div>

  <div class="field">
    <%= f.label :mision %>
    <%= f.text_area :mision %>
  </div>

  <div class="field">
    <%= f.label :vision %>
    <%= f.text_area :vision %>
  </div>

  <div class="field">
    <%= f.label :descripcion %>
    <%= f.text_area :descripcion %>
  </div>

  <div class="field">
    <%= f.label :contactenos %>
    <%= f.text_field :contactenos %>
  </div>

  <div class="field">
    <%= f.label :copyright %>
    <%= f.text_field :copyright %>
  </div>

  <div class="field">
    <%= f.label :urlnosotros %>
    <%= f.file_field :urlnosotros %>
  </div>

  <div class="field">
    <%= f.label :urlmision %>
    <%= f.file_field :urlmision %>
  </div>

  <div class="field">
    <%= f.label :urlvision %>
    <%= f.file_field :urlvision %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/aboutus/edit.html.erb
<h1>Editing Aboutu</h1>

<%= render 'form', aboutu: @aboutu %>

<% if !current_user.nil? %> 
    <% if current_user.user_role? %>
      <%= link_to 'Show', @aboutu %> |
	  <%= link_to 'Back', aboutus_path %>
    <% end %>
  <% end %>

app/views/aboutus/index.html.erb
  <% @aboutus.each do |aboutu| %>

    <div id="portafolio" class="container-full-bg">
      <div class="container special">
        <div><br><br><h1 class="text-center"><%= link_to 'PORTAFOLIO', productos_path %></h1><br>
          <!-- Carousel ========================================== -->
          <div align="center" id="myProductCarousel" class="carousel slide carousel-left" data-interval="3500" data-ride="carousel">
            <!-- Indicators -->
            <ol class="carousel-indicators">
              <li data-target="#myProductCarousel" data-slide-to="0" class="active"></li>
              <li data-target="#myProductCarousel" data-slide-to="1"></li>
              <li data-target="#myProductCarousel" data-slide-to="2"></li>
            </ol>
            <div class="carousel-inner" role="listbox">
              <div class="item active">
                <img class="first-slide img_thumb_slide" src="/intgm-demarcacion.png" alt="First slide" style="float: left; margin-left:120px; margin-right: 30px;">
                <div class="container">
                  <div class="carousel-caption" style="text-align:right;">
                    <h1 class="text-primary">Demarcaci&oacute;n de v&iacute;as</h1>
                    <p class="text-muted">Todo lo relacionado con pinturas, abrasivos, pistolas</p>
                  </div>
                </div>
              </div>
              <div class="item">
                <img class="second-slide img_thumb_slide" src="/intgm-marcas.png" alt="Second slide" style="float: left; margin-left:120px; margin-right: 30px;">
                <div class="container">
                  <div class="carousel-caption" style="text-align:right;">
                    <h1 class="text-primary">Marcas recomendadas</h1>
                    <p class="text-muted">La reparaci&oacute;n de equipos incluye partes de Graco y Tit&aacute;n</p>
                  </div>
                </div>
              </div>
              <div class="item">
                <img class="third-slide img_thumb_slide" src="/intgm-reparacion.png" alt="Third slide" style="float: left; margin-left:120px; margin-right: 30px;">
                <div class="container">
                  <div class="carousel-caption" style="text-align:right;">
                    <h1 class="text-primary">Reparamos equipos</h1>
                    <p class="text-muted">Ofrecemos servicios de reparaci&oacute;n de equipos Graco y Tit&aacute;n</p>
                  </div>
                </div>
              </div>
            </div>
            <a class="left carousel-control" href="#myProductCarousel" role="button" data-slide="prev">
              <span class="glyphicon glyphicon-chevron-left text-primary" aria-hidden="true"></span>
              <span class="sr-only">Previous</span>
            </a>
            <a class="right carousel-control" href="#myProductCarousel" role="button" data-slide="next">
              <span class="glyphicon glyphicon-chevron-right text-primary" aria-hidden="true"></span>
              <span class="sr-only">Next</span>
            </a>
          </div><!-- /.carousel portafolio -->
        <br><br>
        </div>

        <!-- Container (Contacto Section) -->
        <div id="contacto" class="container-fluid bg-grey" style="background-color: #f9f9f9;">
          <div class="row">
            <div class="col-sm-4">
              <%= link_to new_contacto_path do %>
                <i class="glyphicon glyphicon-globe glyphlogo slideanim" style="font-size: 200px;"></i>
              <% end %>&nbsp;
            </div>
            <div class="col-sm-8">
              <h1><%= link_to 'CONTÁCTENOS', new_contacto_path %></h1><br>
              <h4 class="text-justify">Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.</h4>
            </div>
          </div>
        </div>

        <!-- Container (Nosotros Section) -->
        <div id="nosotros" class="container-fluid">
          <div class="row">
            <div class="col-sm-8">
              <% @nosotrosabt = aboutus_path + '/1' %>
              <h1><%= link_to 'NOSOTROS', @nosotrosabt %></h1><br>
              <h4 class="text-justify"><%= aboutu.descripcion %></h4><br>
            </div>
            <div class="col-sm-4 text-primary">
              <a href="<%= @nosotrosabt %>">
                <i class="glyphicon glyphicon-hand-left glyphlogo slideanim" style="font-size: 170px;"></i>
              </a><br>&nbsp;
            </div>
          </div>
        </div>

      </div>
    </div>

    <% if !current_user.nil? %> 
      <% if current_user.user_role? %>
        <%= link_to 'Show', aboutu %>
      <% end %>
    <% end %>

  <% end %>

app/views/aboutus/new.html.erb
<%= render 'form', aboutu: @aboutu %>

<% if !current_user.nil? %> 
    <% if current_user.user_role? %>
      <%= link_to 'Back', aboutus_path %>
    <% end %>
  <% end %>

app/views/aboutus/show.html.erb
<br><br>
  
  <div class="container special">
    <center>
      <img src="../../../logo.png" class="img-rounded" alt="Logo Integral GM" width="524" height="228">
    </center><br>
  </div>

  <div class="container special bg-primary">
    <!-- Example row of columns -->
    
    <div class="row">
      <div class="col-md-4"><center>
        <br><br><%=image_tag @aboutu.urlmision, class: 'img' %>
        <h2 class="text-center">Misi&oacute;n</h2></center>
        <p class="text-justify"><%= @aboutu.mision %></p>
      </div>
      <div class="col-md-4"><center>
        <br><br><%=image_tag @aboutu.urlvision, class: 'img' %>
        <h2 class="text-center">Visi&oacute;n</h2></center>
        <p class="text-justify"><%= @aboutu.vision %></p>
      </div>
      <div class="col-md-4"><center>
        <br><br><%=image_tag @aboutu.urlnosotros, class: 'img' %>
        <h2 class="text-center"> Cont&aacute;ctenos </h2></center>
        <p>
          <p><span class="glyphicon glyphicon-envelope"></span>
            &nbsp; contacto@integralgmsas.com </p>
          <p><span class="glyphicon glyphicon-map-marker"></span> 
            &nbsp; Carrera 5 # 60 - 147</p>
            <p style="margin-left: 27px;">Cali, Valle</p> 
            <p style="margin-left: 27px;">760004</p> 
            <p style="margin-left: 27px;">Colombia</p> 
          <p><span class="glyphicon glyphicon-phone-alt"></span>
            &nbsp;(+572) 3737391</p>
          <p><span class="glyphicon glyphicon-phone"></span>
            &nbsp;(+57) 3163737391</p>
        </p>
      </div>
    </div>
    <br>
  </div>
  <br><br>

  <!-- Map -->
  <section id="contact" class="map">
    <center>
      <iframe src="https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d3982.522232937395!2d-76.49370795014795!3d3.465550952081271!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x8e30a7c88605298d%3A0x7c72a7254705c66!2sCra.+5+%2360-147%2C+Cali%2C+Valle+del+Cauca!5e0!3m2!1ses!2sco!4v1486943605884" width="90%" height="350" frameborder="0" style="border:0"  scrolling="no" marginheight="0" marginwidth="0" allowfullscreen></iframe>
      <br />
      <small>
          <a href="https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d3982.522232937395!2d-76.49370795014795!3d3.465550952081271!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x8e30a7c88605298d%3A0x7c72a7254705c66!2sCra.+5+%2360-147%2C+Cali%2C+Valle+del+Cauca!5e0!3m2!1ses!2sco!4v1486943605884"></a>
      </small>
    </center>
  </section>
  <br>

  <% if !current_user.nil? %> 
    <% if current_user.user_role? %>
      <%= link_to 'Edit', edit_aboutu_path(@aboutu) %> |
      <%= link_to 'Back', aboutus_path %>
    <% end %>
  <% end %>