config/routes.rb
Rails.application.routes.draw do
  
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  resources :contactos
  resources :aboutus
  resources :producto_adjuntos
  resources :productos
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'aboutus#index'
  get 'search/create'

  # User authentication
  devise_for :users, controllers: {
    sessions: 'users/sessions',
    passwords: 'users/passwords',
    registrations: 'users/registrations'
  }

end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Integralgm</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <!--[if lt IE 9]>
      <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/r29/html5.min.js">
      </script>
    <![endif]-->
    <% unless flash.empty? %>
      <script type="text/javascript">
          <% flash.each do |f| %>
              <% type = f[0].to_s.gsub('alert', 'error').gsub('notice', 'info') %>
              toastr['<%= type %>']('<%= f[1] %>', '', {"closeButton": false, "debug": false, "positionClass": "toast-bottom-full-width", "onclick": null, "showDuration": "300", "hideDuration": "1000", "timeOut": "5000", "extendedTimeOut": "1000", "showEasing": "swing", "hideEasing": "linear", "showMethod": "fadeIn", "hideMethod": "fadeOut" });
          <% end %>
      </script>
    <% end %>
    </script>
  </head>
  <body data-spy="scroll" data-target=".navbar" data-offset="60" onload="startTime();checkTRM();">

    <!-- NAVBAR -->
    <nav class="navbar navbar-default navbar-fixed-top">
      <div class="container">
        <div class="navbar-header">
          <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbarigm" aria-expanded="false" aria-controls="navbar">
            <span class="sr-only"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          <a class="navbar-brand" href="#" style="padding-right: 8em;">
            <img src="../../logo.png" class="img-rounded navbar-logo" alt="Integral GM" width="169" height="57" style="margin-top: 2px;">
          </a>&nbsp;
        </div>
        <div id="navbarigm" class="navbar-collapse collapse">
          
              <ul class="nav navbar-nav navbar-left">
                <li class="<%= 'active' if current_page?(root_path) %>">
                  <%= link_to 'Inicio', root_path %></li>

                <li class="<%= 'active' if current_page?(productos_path) %>">
                  <% if current_page?(root_path) %>
                    <a href="#portafolio">Portafolio</a>
                  <% else %>
                    <%= link_to 'Portafolio', productos_path %>
                  <% end %>
                </li>

                <li class="<%= 'active' if current_page?(new_contacto_path) %>">
                  <% if current_page?(root_path) %>
                    <a href="#contacto">Cont&aacute;ctenos</a>
                  <% else %>
                    <%= link_to 'Contáctenos', new_contacto_path %>
                  <% end %>
                </li>

                <li class="<%= 'active' if current_page?(aboutus_path) %>">
                  <% if current_page?(root_path) %>
                    <a href="#nosotros">Nosotros</a>
                  <% else %>
                    <% @nosotros = aboutus_path + '/1' %>
                    <%= link_to 'Nosotros', @nosotros %>
                  <% end %>
                </li>
              </ul>
            
              <ul class="nav navbar-nav pull-right">
                <% if user_signed_in? %>

                  <% if !current_user.nil? && current_user.superadmin_role? %>
                    <li> <%= link_to rails_admin_path do %>
                        <i class="glyphicon glyphicon-dashboard"></i> Admin
                    <% end %> </li>
                  <% end %>   
                  <li><i><%= link_to(truncate(current_user.email, :length => 10, :separator => '@'), edit_user_registration_path) %></i></li>
                  <li><%= link_to('Salir', destroy_user_session_path, :method => :delete) %></li>
                  
                <% else %>
                  
                  <li> <%= link_to new_user_session_path do %>
                      <i class="glyphicon glyphicon-log-in"></i> Login
                  <% end %> </li>
                <% end %>
              </ul>
            
        </div>
      </div>
    </nav>
    <!-- ===== END NAVBAR ===== -->
    <!-- MENU FLOTANTE Busqueda, Hora Colombia, TRM -->
    <nav class="floating-menu">
      <div id="mySidenav" class="sidenav">
        <a id="blog" class="row" style="height: 47px;" onmouseover="javascript:checkTRM();">
          <div class="row" style="color: white;">
          <div class="col-xs-4 col-sm-4 col-lg-4">
              <span class="glyphicon glyphicon-paperclip" style="font-size: 18px; margin-right: 4px;"></span>
              <div class="text-center" id="txTime" style="margin-top: -24px;"></div>&nbsp;
            </div>
            <div class="col-xs-4 col-sm-4 col-lg-4" onclick="redirTRM();return false">
              <div id="IframeWrapper" style="position: relative;" width="200" height="27">
                <iframe id="frameTRM" width="200" height="27" style="border:0;margin-top: -6px;"></iframe>
                <div id="iframeBlocker" style="position:absolute; top: 0; left: 0; width:95%; height:95%;background-color:none;opacity:0.1;"></div>
              </div>
            </div>
            <div class="col-xs-4 col-sm-4 col-lg-4" style="margin-top: -9px;">
              <%= form_tag "/search/create", method: 'get', remote: true, class: 'navbar-form  navbar-right', role: 'search' do %>
                <div class="input-group-sm">
                  <%= text_field_tag :keyword, nil, size: 25, placeholder: "Buscar...", class: "form-control"%>
                  <span class="input-group-addon-sm"><i class="glyphicon glyphicon-search"><%= submit_tag " ", class: 'hidden' , data: {target: "#myModalSearch", toggle: "modal"} %></i></span>
                </div>
              <% end %>
            </div>
          </div>
        </a>
      </div>
    </nav>
    <!-- JUMBOTRON -->
    <% if current_page?(root_path) %>
      <div class="jumbotronx text-center">
        <h1>INTEGRAL GM SAS</h1>
        <h2>Productos y Servicios</h2>
      </div>
    <% end %>
    <br><br>
    <!-- MAIN CONTENT-->
  	<div id="main-container" class="container">
      <div class="row">
        <div id="main-content"><br>
          <% if notice %><br>
            <div class="alert alert-info alert-dismissable fade in" role="alert">
            <a href="/" class="close" data-dismiss="notice" aria-label="close">&times;</a>
            <%= notice %></div>
          <% end %>

          <% if alert %><br>
            <div class="alert alert-warning alert-dismissable fade in" role="notice">
            <a href="#" class="close" data-dismiss="alert" aria-label="close">&times;</a>
            <%= alert %></div>
          <% end %>

          <!-- Modal -->
          <div id="myModalSearch" class="modal fade" role="dialog" style="display: none; z-index: 1050; margin-top: 30px;">
            <div class="modal-dialog">
              <!-- Modal content-->
              <div class="modal-content">
                <div class="modal-header">
                  <button type="button" class="close" data-dismiss="modal">&times;</button>
                  <h4 class="modal-title">Resultados de la b&uacute;squeda</h4>
                </div>
                <div class="modal-body">
                  <div id="resultados"></div>
                </div>
              </div>

            </div>
          </div>

          <%= yield %>

        </div>
      </div>
    </div>

    <!-- FOOTER -->
    <br>
    <footer class="container-fluid text-center bg-grey" style="background-color: #f9f9f9">
      <a href="#" title="Subir">
        <span class="glyphicon glyphicon-chevron-up"></span>
      </a>

      <!-- Container (Contenido - Contacto - Mas - Section) -->
      <div class="container-fluid text-justify">
        <div class="row">
          <div class="col-sm-4">
            <h4><span class="glyphicon glyphicon-off"></span>&nbsp;CONTENIDO</h4> 
            <hr>
            <p>
              <%= link_to 'Inicio', root_path %>
              <br><br><%= link_to 'Portafolio', productos_path %>
              <br><br><%= link_to 'Contáctenos', new_contacto_path %>
              <br><br><% @nosotrosftr = aboutus_path + '/1' %><%= link_to 'Nosotros', @nosotrosftr %>
            </p>
          </div>
          <div class="col-sm-4">
            <h4><span class="glyphicon glyphicon-globe"></span>&nbsp;CONT&Aacute;CTENOS</h4>
            <hr>
            <p>
              <p><span class="glyphicon glyphicon-envelope"></span>
                &nbsp; contacto@integralgmsas.com </p>
              <p><span class="glyphicon glyphicon-map-marker"></span> 
                &nbsp; Carrera 5 # 60 - 147</p>
                <p style="margin-left: 27px;">Cali, Valle</p> 
                <p style="margin-left: 27px;">760004</p> 
                <p style="margin-left: 27px;">Colombia</p> 
              <p><span class="glyphicon glyphicon-phone-alt"></span>
                &nbsp;(+572) 3737391</p>
              <p><span class="glyphicon glyphicon-phone"></span>
                &nbsp;(+57) 3163737391</p>
            </p>
          </div>
          <div class="col-sm-4">
            <h4><span class="glyphicon glyphicon-cog"></span>&nbsp;PORTAFOLIO</h4>
            <hr>
            <div>
              <%= form_tag "/search/create", method: 'get', remote: true, class: 'navbar-form  navbar-left', role: 'search' do %>
              <div class="input-group-sm">
                <%= text_field_tag :keyword, nil, size: 25, placeholder: "Buscar en portafolio...", class: "form-control"%>
                <span class="input-group-addon-sm"><i class="glyphicon glyphicon-search"><%= submit_tag " ", class: 'hidden' , data: {target: "#myModalSearch", toggle: "modal"} %></i></span>
              </div>
              <% end %>
            </div>
          </div>
        </div>
      </div>
      <p>&copy; 2017 &middot; Integral GM &middot; SAS 
        <% if user_signed_in? %> &middot; En sesi&oacute;n <i><%= current_user.email %> </i><% end %>
      </p>
    </footer><br>

<script>
$(document).ready(function(){
  // Taken from w3schools
  // Add smooth scrolling to all links in navbar + footer link
  $(".navbar a, footer a[href='#']").on('click', function(event) {
    // Make sure this.hash has a value before overriding default behavior
    if (this.hash !== "") {
      // Prevent default anchor click behavior
      event.preventDefault();

      // Store hash
      var hash = this.hash;

      // Using jQuery's animate() method to add smooth page scroll
      // The optional number (900) specifies the number of milliseconds it takes to scroll to the specified area
      $('html, body').animate({
        scrollTop: $(hash).offset().top
      }, 900, function(){
   
        // Add hash (#) to URL when done scrolling (default click behavior)
        window.location.hash = hash;
      });
    } // End if
  });
  
  $(window).scroll(function() {
    $(".slideanim").each(function(){
      var pos = $(this).offset().top;

      var winTop = $(window).scrollTop();
        if (pos < winTop + 600) {
          $(this).addClass("slide");
        }
    });
  });
})
</script>

  </body>
</html>